### ISSUE TITLE
Leaks in server

### ISSUE THREAD

**Issue by hferraud** [Mururoahh/Cub3D#25]

**Comment by Mururoahh** [comment]
=================================================================
==701169==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 16 byte(s) in 1 object(s) allocated from:
    #0 0x7fbdcdfb1808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x562e8d0cadcf in ft_lstnew (/nfs/homes/hferraud/cursus/circle-4/cub3D/cub3D_server+0xcdcf)
    #2 0x562e8d0ca12d in listen_connections (/nfs/homes/hferraud/cursus/circle-4/cub3D/cub3D_server+0xc12d)

Indirect leak of 4 byte(s) in 1 object(s) allocated from:
    #0 0x7fbdcdfb1808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x562e8d0ca0fe in listen_connections (/nfs/homes/hferraud/cursus/circle-4/cub3D/cub3D_server+0xc0fe)

SUMMARY: AddressSanitizer: 20 byte(s) leaked in 2 allocation(s).
